# Docker Compose for NeuroDoc
version: '3.8'

services:
  neurodoc:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONPATH=/app
    volumes:
      # Mount data directory to persist knowledge base and sessions
      - ./data:/app/data
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
